services:
  backend:
    ports:
      - "9000:8000"

  mariadb:
    ports:
      - "3306:3306"

  adminer:
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8090:8080"
    depends_on:
      - mariadb
    networks:
      - svitbo
