services:
  backend:
    build:
      context: ..
      dockerfile: compose.d/Dockerfile.backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - svitbo

  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - svitbo

networks:
  svitbo:

volumes:
  db_data:
