services:
  backend:
    ports:
      - "9000:8000"

  mariadb:
    ports:
      - "4472:3306"

  adminer:
    image: adminer:4
    container_name: svitbo-adminer
    restart: unless-stopped
    ports:
      - "9292:8080"
    depends_on:
      - mariadb
    networks:
      - general
