FROM python:3.12-slim AS builder

RUN apt-get update && \
    apt-get install -y \
        default-libmysqlclient-dev \
        pkg-config \
        gcc

WORKDIR /app

COPY requirements.txt .

RUN python3 -m venv venv && \
    . venv/bin/activate && \
    pip install --no-cache-dir -r requirements.txt

# Final image to build
FROM python:3.12-slim

ENV PATH="/app/venv/bin:$PATH"

WORKDIR /app

COPY --from=builder /app/venv ./venv

COPY . .

EXPOSE 8000

ENTRYPOINT ["./entrypoint.sh"]
