name: Deploy to GCP

on:
  push:
    branches:
      - main
      - develop
      - add-gh-actions-gcp-deployment # Remove later

jobs:
  pull-code:
    runs-on: ubuntu-latest

    steps:
      - name: "Deploy core to the GCP"
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            BRANCH="main"
            INSTANCE_NAME="${{ secrets.PROD_GCP_INSTANCE_NAME }}"
            ZONE="${{ secrets.PROD_GCP_ZONE }}"
          elif [[ "${{ github.ref }}" == "refs/heads/add-gh-actions-gcp-deployment" ]]; then
            BRANCH="develop"
            INSTANCE_NAME="${{ secrets.DEV_GCP_INSTANCE_NAME }}"
            echo "SSH_PRIVATE_KEY=${{ secrets.DEV_GCP_SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
            ZONE="${{ secrets.DEV_GCP_ZONE }}"
          else
            echo "Not a main or develop branch. Well, we shouldn't be here at all"
            # exit 0
          fi

      - name: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "$CREDENTIALS"

      - name: "?????"
        uses: "google-github-actions/ssh-compute@v1"
        with:
          instance_name: "$INSTANCE"
          zone: "$ZONE"
          ssh_private_key: "$SSH_PRIVATE_KEY"
          command: "whoami && pwd"
